/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import camera.Camera;
import java.awt.Color;
import java.awt.color.ColorSpace;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFrame;

/**
 *
 * @author miguel
 */
public class Window extends javax.swing.JPanel {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jSlider4 = new javax.swing.JSlider();
        jSlider5 = new javax.swing.JSlider();
        jSlider6 = new javax.swing.JSlider();

        setMinimumSize(new java.awt.Dimension(45, 45));
        setLayout(new java.awt.BorderLayout(12, 12));

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(640, 360));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setViewportView(jLabel1);

        jPanel1.add(jScrollPane1);

        jScrollPane2.setViewportView(jLabel2);

        jPanel1.add(jScrollPane2);

        jLabel3.setToolTipText("");
        jScrollPane3.setViewportView(jLabel3);

        jPanel1.add(jScrollPane3);

        jScrollPane4.setViewportView(jLabel4);

        jPanel1.add(jScrollPane4);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(2, 6));

        jLabel5.setText("HueMin");
        jPanel2.add(jLabel5);

        jLabel6.setText("HueMax");
        jPanel2.add(jLabel6);

        jLabel7.setText("SaturationMin");
        jPanel2.add(jLabel7);

        jLabel8.setText("SaturationMax");
        jPanel2.add(jLabel8);

        jLabel9.setText("ValueMin");
        jPanel2.add(jLabel9);

        jLabel10.setText("ValueMax");
        jPanel2.add(jLabel10);

        jSlider1.setMajorTickSpacing(20);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setPaintTrack(false);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hue(evt);
            }
        });
        jPanel2.add(jSlider1);

        jSlider2.setMajorTickSpacing(20);
        jSlider2.setMinorTickSpacing(5);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setPaintTrack(false);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hue(evt);
            }
        });
        jPanel2.add(jSlider2);

        jSlider3.setMajorTickSpacing(50);
        jSlider3.setMaximum(255);
        jSlider3.setMinorTickSpacing(10);
        jSlider3.setPaintLabels(true);
        jSlider3.setPaintTicks(true);
        jSlider3.setPaintTrack(false);
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hue(evt);
            }
        });
        jPanel2.add(jSlider3);

        jSlider4.setMajorTickSpacing(50);
        jSlider4.setMaximum(255);
        jSlider4.setMinorTickSpacing(10);
        jSlider4.setPaintLabels(true);
        jSlider4.setPaintTicks(true);
        jSlider4.setPaintTrack(false);
        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hue(evt);
            }
        });
        jPanel2.add(jSlider4);

        jSlider5.setMajorTickSpacing(50);
        jSlider5.setMaximum(255);
        jSlider5.setMinorTickSpacing(10);
        jSlider5.setPaintLabels(true);
        jSlider5.setPaintTicks(true);
        jSlider5.setPaintTrack(false);
        jSlider5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hue(evt);
            }
        });
        jPanel2.add(jSlider5);

        jSlider6.setMajorTickSpacing(50);
        jSlider6.setMaximum(255);
        jSlider6.setMinorTickSpacing(10);
        jSlider6.setPaintLabels(true);
        jSlider6.setPaintTicks(true);
        jSlider6.setPaintTrack(false);
        jSlider6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hue(evt);
            }
        });
        jPanel2.add(jSlider6);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void hue(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hue
        // TODO add your handling code here:
        Camera.setHsvRange(jSlider1.getValue(), jSlider3.getValue(), jSlider5.getValue(),
                jSlider2.getValue(), jSlider4.getValue(), jSlider6.getValue());
    }//GEN-LAST:event_hue

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JSlider jSlider6;
    // End of variables declaration//GEN-END:variables

    public synchronized void setImageIcon(ImageIcon ... imageIcon) {
        try {
            jLabel1.setIcon(imageIcon[0]);
            jLabel2.setIcon(imageIcon[1]);
            jLabel3.setIcon(imageIcon[2]);
            jLabel4.setIcon(imageIcon[3]);
        } catch (ArrayIndexOutOfBoundsException e) {
            e.printStackTrace();
        }
    }
    
}
